sudo: true
dist: trusty

env:
  - COMPOSE_FILE=docker/travis.yml

services:
  - docker

# cache vendor dirs
cache:
  directories:
    - vendor

install:
  - cp .env.dist .env
  - docker-compose up --build --force-recreate --remove-orphans -d
  - docker-compose exec -T app composer install --dev --prefer-source --no-interaction
  - docker-compose exec -T app ./vendor/bin/codecept build

before_script:
  - docker-compose exec -T db mysql -uroot -proot -e "CREATE DATABASE \`yii2-starter-kit-test\`"
  - docker-compose exec -T app php console/yii app/setup --interactive=0
  - docker-compose exec -T app php console/yii app/truncate --interactive=0

script:
  - docker-compose exec -T php -S localhost:8080 > /dev/null 2>&1 &
  - docker-compose exec -T php ./vendor/bin/codecept run --debug
